### ISSUE TITLE
[BUG]: Config file not loading correctly

### ISSUE THREAD

**Issue by NVGAT** [spartacus04/InstantRestock#59]
The plugins throws an error into the console when trying to enable on 1.20.6. The error is as follows:
```[17:03:35 ERROR]: Error occurred while enabling InstantRestock v2.4.2 (Is it up to date?)
java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) ~[?:?]
        at java.base/java.util.Objects.checkIndex(Objects.java:385) ~[?:?]
        at java.base/java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at instantrestock_2.4.2.jar/me.spartacus04.instantrestock.SettingsContainer$Companion.reloadConfig(Settings.kt:50) ~[instantrestock_2.4.2.jar:?]
        at instantrestock_2.4.2.jar/me.spartacus04.instantrestock.InstantRestock.onEnable(InstantRestock.kt:21) ~[instantrestock_2.4.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:git-Paper-53]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:git-Paper-53]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.6.jar:git-Paper-53]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:682) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:441) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:324) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1140) ~[paper-1.20.6.jar:git-Paper-53]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[paper-1.20.6.jar:git-Paper-53]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### Describe alternatives you've considered.

I've considered a similar datapack version of this plugin, but it also has problems with 1.20.6.

### Additional context

This is (obviously) using the new experimental builds of PaperMC.

**Comment by spartacus04** [comment]
Hello, the issue is actually related to the loading of the config file, I'll fix it ASAP.
By the way, you used the Feature Request template instead of the bug report one.

**Comment by NVGAT** [comment]
> Hello, the issue is actually related to the loading of the config file, I'll fix it ASAP.
> By the way, you used the Feature Request template instead of the bug report one.

Thanks for the quick response! I'll pay more attention in the future :D

**Comment by spartacus04** [comment]
I just released the update on github/modrinth/hangar, I'll post it soon on Spigot.
